name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: hck
            asset_name: hck-linux-amd64
          - os: macos-latest
            artifact_name: hck
            asset_name: hck-macos-amd64
          # - os: windows-latest
          #   artifact_name: hck
          #   asset_name: windows-macos-amd64

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM Tools
        run: rustup component add llvm-tools-preview

      - name: Build
        run: bash pgo.sh
        # run: cargo build --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
